In [40]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [41]:
df = pd.read_csv('heart.csv')

In [42]:
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [43]:
df.shape

(303, 14)

In [44]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [45]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [46]:
d1=pd.get_dummies(df['cp'],drop_first=True,prefix='cp')
d2=pd.get_dummies(df['thal'],drop_first=True,prefix='thal')
d3=pd.get_dummies(df['slope'],drop_first=True,prefix='slope')
df=pd.concat([df,d1,d2,d3],axis=1)
df.drop(['cp','thal','slope'],axis=1,inplace=True)
df.head()

age  sex  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  ca  \
0   63    1       145   233    1        0      150      0      2.3   0   
1   37    1       130   250    0        1      187      0      3.5   0   
2   41    0       130   204    0        0      172      0      1.4   0   
3   56    1       120   236    0        1      178      0      0.8   0   
4   57    0       120   354    0        1      163      1      0.6   0   

   target  cp_1  cp_2  cp_3  thal_1  thal_2  thal_3  slope_1  slope_2  
0       1     0     0     1       1       0       0        0        0  
1       1     0     1     0       0       1       0        0        0  
2       1     1     0     0       0       1       0        0        1  
3       1     1     0     0       0       1       0        0        1  
4       1     0     0     0       0       1       0        0        1

In [47]:
df['seniors'] = df['age'].map(lambda s: 1 if s >= 60 else 0)

In [48]:
from sklearn.preprocessing import StandardScaler

In [49]:
scaler = StandardScaler()

In [50]:
df_stand_age = scaler.fit_transform(df[['age']])

In [51]:
df_stand_trestbps = scaler.fit_transform(df[['trestbps']])

In [52]:
df_stand_chol = scaler.fit_transform(df[['chol']])

In [53]:
df_stand_thalach = scaler.fit_transform(df[['thalach']])

In [54]:
df_stand_old_peak = scaler.fit_transform(df[['oldpeak']])

In [55]:
df.columns

Index(['age', 'sex', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang',
       'oldpeak', 'ca', 'target', 'cp_1', 'cp_2', 'cp_3', 'thal_1', 'thal_2',
       'thal_3', 'slope_1', 'slope_2', 'seniors'],
      dtype='object')

In [56]:
df.drop(columns = ['age','trestbps','chol','thalach','oldpeak'],inplace=True)

In [57]:
df.columns

Index(['sex', 'fbs', 'restecg', 'exang', 'ca', 'target', 'cp_1', 'cp_2',
       'cp_3', 'thal_1', 'thal_2', 'thal_3', 'slope_1', 'slope_2', 'seniors'],
      dtype='object')

In [58]:
df = pd.concat([df,df1],axis=1)

In [59]:
df1 = pd.DataFrame(df_stand_age,columns = ['stand_age'])
df2 = pd.DataFrame(df_stand_trestbps,columns = ['stand_trestbps'])
df3 = pd.DataFrame(df_stand_chol,columns = ['stand_chol'])
df4 = pd.DataFrame(df_stand_thalach,columns = ['tand_thalach'])
df5 = pd.DataFrame(df_stand_old_peak,columns = ['stand_old_peak'])

In [60]:
df = pd.concat([df,df1,df2,df3,df4,df5],axis=1)

In [62]:
X=df.drop('target',axis=1)
y=df['target']

In [63]:
from sklearn.model_selection import train_test_split

In [68]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [79]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

In [80]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

In [71]:
clf1=LogisticRegression()
clf1.fit(x_train,y_train)
LR_pred=clf1.predict(x_test)


print("Accuracy - ",accuracy_score(y_test,LR_pred))
print("Confusion Matrix,-\n", confusion_matrix(y_test,LR_pred))
print("Precision : ", precision_score(y_test,LR_pred))
print("Recall :", recall_score(y_test,LR_pred))
print("F1-Score : ", f1_score(y_test,LR_pred))

Accuracy -  0.9016393442622951
Confusion Matrix,-
 [[27  2]
 [ 4 28]]
Precision :  0.9333333333333333
Recall : 0.875
F1-Score :  0.9032258064516129


In [73]:
RF_model = RandomForestClassifier()
RF_model.fit(x_train,y_train)
RF_pred=RF_model.predict(x_test)

print("Accuracy - ",accuracy_score(y_test,RF_pred))
print("Confusion Matrix,-\n", confusion_matrix(y_test,RF_pred))
print("Precision : ", precision_score(y_test,RF_pred))
print("Recall :", recall_score(y_test,RF_pred))
print("F1-Score : ", f1_score(y_test,RF_pred))

Accuracy -  0.8688524590163934
Confusion Matrix,-
 [[26  3]
 [ 5 27]]
Precision :  0.9
Recall : 0.84375
F1-Score :  0.870967741935484


In [74]:
DT_model = DecisionTreeClassifier()
DT_model.fit(x_train,y_train)
DT_pred=DT_model.predict(x_test)

print("Accuracy - ",accuracy_score(y_test,DT_pred))
print("Confusion Matrix,-\n", confusion_matrix(y_test,DT_pred))
print("Precision : ", precision_score(y_test,DT_pred))
print("Recall :", recall_score(y_test,DT_pred))
print("F1-Score : ", f1_score(y_test,DT_pred))

Accuracy -  0.8360655737704918
Confusion Matrix,-
 [[25  4]
 [ 6 26]]
Precision :  0.8666666666666667
Recall : 0.8125
F1-Score :  0.8387096774193549


In [77]:
knn_model=KNeighborsClassifier()
knn_model.fit(x_train,y_train)
knn_pred=knn_model.predict(x_test)

print("Accuracy - ",accuracy_score(y_test,knn_pred))
print("Confusion Matrix,-\n", confusion_matrix(y_test,knn_pred))
print("Precision : ", precision_score(y_test,knn_pred))
print("Recall :", recall_score(y_test,knn_pred))
print("F1-Score : ", f1_score(y_test,knn_pred))

Accuracy -  0.8524590163934426
Confusion Matrix,-
 [[23  6]
 [ 3 29]]
Precision :  0.8285714285714286
Recall : 0.90625
F1-Score :  0.8656716417910447


In [83]:
svm=SVC(kernel='rbf',C=1)
svm.fit(x_train,y_train)
svm_pred=svm.predict(x_test)

print("Accuracy - ",accuracy_score(y_test,svm_pred))
print("Confusion Matrix,-\n", confusion_matrix(y_test,svm_pred))
print("Precision : ", precision_score(y_test,svm_pred))
print("Recall :", recall_score(y_test,svm_pred))
print("F1-Score : ", f1_score(y_test,svm_pred))

Accuracy -  0.8852459016393442
Confusion Matrix,-
 [[26  3]
 [ 4 28]]
Precision :  0.9032258064516129
Recall : 0.875
F1-Score :  0.8888888888888888
